### PR TITLE
Shellcheck

### PR DESCRIPTION
**Pull request by chrisfinazzo**

### CODE REVIEW

**Comment by ploum** [comment]
Hey,

Any particular reason for this PR ?

**Comment by setop** [comment]
[shellsheck](https://www.shellcheck.net/) is a linter for bash. It advise for shell code good practice. 
Mainly : don't use back quote but dollar parenthesis and double quote every variable so you don't get surprise with space interpolation.

Not sure it worth the effort for a very personal piece of code. Probably very important when you maintain a [ACME (letsencrypt) client consisting of 7500+ line of bash](https://github.com/acmesh-official/acme.sh/blob/1476f83ba71955feb386e3a2f194cb07b6f8f9cc/acme.sh#L7634).

**Comment by chrisfinazzo** [comment]
> [shellsheck](https://www.shellcheck.net/) is a [linter](https://en.wikipedia.org/wiki/Lint_(software)) for bash. It advises for shell code good practices. Mainly : don't use back quote but dollar parenthesis and double quote every variable so you don't get surprise with space interpolation.
> 
> Not sure it worth the effort for a very personal piece of code. Probably very important when you maintain a [ACME (letsencrypt) client consisting of 7500+ line of bash](https://github.com/acmesh-official/acme.sh/blob/1476f83ba71955feb386e3a2f194cb07b6f8f9cc/acme.sh#L7634). It saved my good old 32bit box from trash, that why I'm mentioning it.

This is kind of what I was thinking when I opened the PR. It encourages good practices when writing shell scripts, and sets a baseline of how things should work. Depending on the situation, globbing or splitting may not be what you want, but unquoted variables just seem like a bad idea.

**Comment by ploum** [comment]
thanks a lot for the commit and the explanations. Learned some stuff here :-)

**Pull request merged**
